/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gm.gamcel;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.HeadlessException;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.Iterator;
import java.util.LinkedList;
import java.util.Random;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.JColorChooser;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author CyberXXX
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    private LinkedList<String> raffleNumbers = new LinkedList<String>();
    private String[] raffleNumbersArray;
    private boolean start = false;
    private boolean pause = false;
    private Thread worker;
    private int timer = 50;
    private int column = 1;
    private String captured = "";
    private String currentCol = "";
    private File file;
    //private Image img = Toolkit.getDefaultToolkit().createImage("logo.gif");
    private BufferedImage  img ;
    URL imageURL = this.getClass().getClassLoader().getResource("dark1.jpg");
    private Color color;
    private boolean fullScreen = false;
    private int PrevX,PrevY,PrevWidth,PrevHeight;
    
    public MainFrame() {
        initComponents();
//        SingleInnerPanel.drawImage(background, 0, 0, null);

    }

    public class JBackgroundPanel extends JPanel {

        
        public JBackgroundPanel() {
            // load the background image
            try {
                img = ImageIO.read(imageURL);
            } catch (IOException e) {
                JOptionPane.showMessageDialog(this, e.getMessage());
            }
        }

        @Override
        protected void paintComponent(Graphics g) {
            super.paintComponent(g);
            // paint the background image and scale it to fill the entire space
            g.drawImage(img, 0, 0, getWidth(), getHeight(), this);
        }
    }

    private void start() {
        worker = new Thread() {
            @Override
            public void run() {

                Random rand = new Random();
                start = true;
                while (pause == false) {
                    if (raffleNumbersArray.length < 1) {
                        JOptionPane.showMessageDialog(null, "empty list of raffle numbers.");
                        break;
                    }
                    int index = rand.nextInt(raffleNumbersArray.length - 1);
                    String luckyNumber = raffleNumbersArray[index];
                    char[] larray = luckyNumber.toCharArray();

                    first.setText(Character.toString(larray[0]));
                    second.setText(Character.toString(larray[1]));
                    third.setText(Character.toString(larray[2]));
                    fourth.setText(Character.toString(larray[3]));
                    fifth.setText(Character.toString(larray[4]));
                    sixth.setText(Character.toString(larray[5]));
                    seventh.setText(Character.toString(larray[6]));
                    //System.out.println(Character.toString(larray[2]));

                    try {
                        Thread.sleep(timer);
                    } catch (InterruptedException e) {
                        JOptionPane.showMessageDialog(null, e.getMessage());
                    }
                }
            }
        };

        worker.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fileChooser = new javax.swing.JFileChooser();
        mainTab = new javax.swing.JTabbedPane();
        singleTab3 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        SingleInnerPanel3 = new JBackgroundPanel();
        first3 = new javax.swing.JLabel();
        second3 = new javax.swing.JLabel();
        third3 = new javax.swing.JLabel();
        fourth3 = new javax.swing.JLabel();
        fifth3 = new javax.swing.JLabel();
        sixth3 = new javax.swing.JLabel();
        seventh3 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem10 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        SingleInnerPanel3.setBackground(new java.awt.Color(50, 152, 5));
        SingleInnerPanel3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        SingleInnerPanel3.setForeground(new java.awt.Color(51, 51, 255));
        SingleInnerPanel3.setLayout(new java.awt.GridLayout(1, 0));

        first3.setFont(new java.awt.Font("Tahoma", 3, 265)); // NOI18N
        first3.setForeground(new java.awt.Color(214, 201, 251));
        first3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        first3.setText("9");
        first3.setMaximumSize(new java.awt.Dimension(50, 91));
        SingleInnerPanel3.add(first3);

        second3.setFont(new java.awt.Font("Tahoma", 3, 265)); // NOI18N
        second3.setForeground(new java.awt.Color(214, 201, 251));
        second3.setText("0");
        SingleInnerPanel3.add(second3);

        third3.setFont(new java.awt.Font("Tahoma", 3, 265)); // NOI18N
        third3.setForeground(new java.awt.Color(214, 201, 251));
        third3.setText("0");
        SingleInnerPanel3.add(third3);

        fourth3.setFont(new java.awt.Font("Tahoma", 3, 265)); // NOI18N
        fourth3.setForeground(new java.awt.Color(214, 201, 251));
        fourth3.setText("0");
        SingleInnerPanel3.add(fourth3);

        fifth3.setFont(new java.awt.Font("Tahoma", 3, 265)); // NOI18N
        fifth3.setForeground(new java.awt.Color(214, 201, 251));
        fifth3.setText("0");
        SingleInnerPanel3.add(fifth3);

        sixth3.setFont(new java.awt.Font("Tahoma", 3, 265)); // NOI18N
        sixth3.setForeground(new java.awt.Color(214, 201, 251));
        sixth3.setText("0");
        SingleInnerPanel3.add(sixth3);

        seventh3.setFont(new java.awt.Font("Tahoma", 3, 265)); // NOI18N
        seventh3.setForeground(new java.awt.Color(214, 201, 251));
        seventh3.setText("0");
        SingleInnerPanel3.add(seventh3);

        jScrollPane4.setViewportView(SingleInnerPanel3);

        javax.swing.GroupLayout singleTab3Layout = new javax.swing.GroupLayout(singleTab3);
        singleTab3.setLayout(singleTab3Layout);
        singleTab3Layout.setHorizontalGroup(
            singleTab3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1281, Short.MAX_VALUE)
        );
        singleTab3Layout.setVerticalGroup(
            singleTab3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        mainTab.addTab("Raffle Draw", singleTab3);

        jMenu1.setText("File");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setText("Load Numbers");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem2.setText("Start");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem5.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem5.setText("Reset");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem5);

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_SPACE, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem3.setText("Pause/Resume");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuItem9.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem9.setText("Toggle Fullscreen");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem9);

        jMenuItem4.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem4.setText("Exit");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem4);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");

        jMenuItem6.setText("Change Speed");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem6);

        jMenuItem7.setText("Change Background ");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem7);

        jMenuItem8.setText("Change Text Color");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem8);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Help");

        jMenuItem10.setText("About");
        jMenu3.add(jMenuItem10);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainTab, javax.swing.GroupLayout.DEFAULT_SIZE, 1289, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainTab)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        if (raffleNumbers.size() < 1) {
            JOptionPane.showMessageDialog(this, "Raffle numbers not yet loaded...");
            System.err.println(raffleNumbers.size());
        } else {
            if (worker == null) {
                start();

            } else {
                if (start == false) {
                    start();
                } else {
                    JOptionPane.showMessageDialog(this, "Raffle already started...");
                }

            }

        }

    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        raffleNumbers.clear();
        int retValue = fileChooser.showOpenDialog(this);
        if (retValue == JFileChooser.APPROVE_OPTION) {
            file = fileChooser.getSelectedFile();

            try {
                Scanner raffleNumbersFile = new Scanner(file);
                while (raffleNumbersFile.hasNextLine()) {
                    String item = raffleNumbersFile.nextLine();
                    if (!item.trim().isEmpty()) {
                        if (item.startsWith("+220")) {
                            item = item.replace("+220", "");
                        } else if (item.startsWith("00220")) {
                            item = item.replace("00220", "");
                        }

                        if (item.length() == 7) {
                            raffleNumbers.add(item);
                        }

                    }
                }
                raffleNumbersFile.close();
                int numOfFiles = raffleNumbers.size();
                raffleNumbersArray = new String[numOfFiles];
                raffleNumbersArray = raffleNumbers.toArray(raffleNumbersArray);
                JOptionPane.showMessageDialog(this, numOfFiles + "  numbers loaded...");
            } catch (FileNotFoundException | HeadlessException e) {
                    JOptionPane.showMessageDialog(this, e.getMessage());
            }
        }
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void reloadFile() {
        raffleNumbers.clear();
        try {
            Scanner raffleNumbersFile = new Scanner(file);
            while (raffleNumbersFile.hasNextLine()) {
                String item = raffleNumbersFile.nextLine();
                if (!item.trim().isEmpty()) {
                    if (item.startsWith("+220")) {
                        item = item.replace("+220", "");
                    } else if (item.startsWith("00220")) {
                        item = item.replace("00220", "");
                    }

                    if (item.length() == 7) {
                        raffleNumbers.add(item);
                    }

                }
            }
            raffleNumbersFile.close();
            int numOfFiles = raffleNumbers.size();
            raffleNumbersArray = new String[numOfFiles];
            raffleNumbersArray = raffleNumbers.toArray(raffleNumbersArray);
            JOptionPane.showMessageDialog(this, numOfFiles + "  numbers loaded...");
        } catch (FileNotFoundException | HeadlessException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
            
        }   
    }


    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed

        if (worker == null || start == false) {
            JOptionPane.showMessageDialog(this, "Raffle not yet started...");
        } else {
            if (pause == true) {
                worker.resume();
                pause = false;
            } else {

                worker.suspend();
                pause = true;
                column++;

            }
        }

    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        if (worker == null) {
            JOptionPane.showMessageDialog(this, "No current instance of a raffle...");
            return;
        }
        worker.stop();
        start = false;
        pause = false;
        column = 1;
        captured = "";
        currentCol = "";

        first.setText("9");
        second.setText("0");
        third.setText("0");
        fourth.setText("0");
        fifth.setText("0");
        sixth.setText("0");
        seventh.setText("0");

        reloadFile();

    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        try {
            timer = Integer.parseInt(JOptionPane.showInputDialog("Enter speed (MilliSeconds): ", timer));
        } catch (NumberFormatException e) {
            timer = 50;
            JOptionPane.showMessageDialog(this, "Incorrect Number Format.Please try Again");
        }
        
        
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
       
        int retValue = fileChooser.showOpenDialog(this);
        if (retValue == JFileChooser.APPROVE_OPTION) {
           File image = fileChooser.getSelectedFile();
        try {
            img = ImageIO.read(new File(image.getAbsolutePath()));
            repaint();
        } catch (NumberFormatException e) {
            
            JOptionPane.showMessageDialog(this, "Incorrect Number Format.Please try Again");
        }   catch (IOException ex) {
                Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
        
        }
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        color = JColorChooser.showDialog(this, "Please Choose a Color", Color.WHITE);
        first.setForeground(color);
        second.setForeground(color);
        third.setForeground(color);
        fourth.setForeground(color);
        fifth.setForeground(color);
        sixth.setForeground(color);
        seventh.setForeground(color);
        
        repaint();
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
       if(fullScreen == false){
           PrevX = getX();
           PrevY = getY();
           PrevWidth = getWidth();
           PrevHeight = getHeight();
           dispose();
           setUndecorated(true);
           setBounds(0,0,getToolkit().getScreenSize().width,getToolkit().getScreenSize().height);
           this.setVisible(true);
           fullScreen = true;
       }else{
           setVisible(true);
           setBounds(PrevX, PrevY, PrevWidth, PrevHeight);
           dispose();
           setUndecorated(false);
           setVisible(true);
           fullScreen = false;
       }
       
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
               
                URL url = this.getClass().getClassLoader().getResource("logo1.jpg");
                Toolkit kit = Toolkit.getDefaultToolkit();
                Image img = kit.createImage(url);
                
                MainFrame mainFrame = new MainFrame();
                mainFrame.setIconImage(img);
                mainFrame.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel SingleInnerPanel;
    private javax.swing.JPanel SingleInnerPanel1;
    private javax.swing.JPanel SingleInnerPanel2;
    private javax.swing.JPanel SingleInnerPanel3;
    private javax.swing.JLabel fifth;
    private javax.swing.JLabel fifth1;
    private javax.swing.JLabel fifth2;
    private javax.swing.JLabel fifth3;
    private javax.swing.JFileChooser fileChooser;
    private javax.swing.JLabel first;
    private javax.swing.JLabel first1;
    private javax.swing.JLabel first2;
    private javax.swing.JLabel first3;
    private javax.swing.JLabel fourth;
    private javax.swing.JLabel fourth1;
    private javax.swing.JLabel fourth2;
    private javax.swing.JLabel fourth3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane mainTab;
    private javax.swing.JLabel second;
    private javax.swing.JLabel second1;
    private javax.swing.JLabel second2;
    private javax.swing.JLabel second3;
    private javax.swing.JLabel seventh;
    private javax.swing.JLabel seventh1;
    private javax.swing.JLabel seventh2;
    private javax.swing.JLabel seventh3;
    private javax.swing.JPanel singleTab;
    private javax.swing.JPanel singleTab1;
    private javax.swing.JPanel singleTab2;
    private javax.swing.JPanel singleTab3;
    private javax.swing.JLabel sixth;
    private javax.swing.JLabel sixth1;
    private javax.swing.JLabel sixth2;
    private javax.swing.JLabel sixth3;
    private javax.swing.JLabel third;
    private javax.swing.JLabel third1;
    private javax.swing.JLabel third2;
    private javax.swing.JLabel third3;
    // End of variables declaration//GEN-END:variables
}
